Pool.create(name: 'PISCINE SUZANNE BERLIOUX (LES HALLES)',
            address: 'forum des Halles 75001 PARIS',
            opening_times: '',
            price: '',
            phone: '',
            metro: '',
            open: true,
            size:,
            lane:,
            treatment: '')
